### ISSUE TITLE
Support an attribute replacement approach

### ISSUE THREAD

**Issue by LightGuard** [LightGuard/asciidoc-splitter#1]
The kogito docs current use an attribute called `:replaceWith:` It is currently not kown where this attribute can be placed. Ideally it would be within a block or section making it easier to look for.

The idea is that the value of the attribute will point to another fragment or module. I'm open to making this an include macro instead of a special post processor step.

**Comment by LightGuard** [comment]
@manaswinidas I'd like you to take a look at this. Some pros and cons of both approaches here would be helpful and we can make a decision based on that.

**Comment by LightGuard** [comment]
I have discovered today that attributes in the asciidoctor API are a complicated beast. The best way to work with them is through a TreeProcessor and using the `getAttribute(String, Object, boolean)` method like so: `block.getAttribute("my-attribute", null, true)` if that returns null then the attribute doesn't exist, otherwise it will return the value either at the block level or at the document level if the attribute doesn't exist on the block.

I have also discovered that attributes that are defined using the `[name=value]` syntax above a block works much better in the API than the `:name: value` syntax. I believe this has to do with the difference between document attributes (and redefining them) and block attributes.

**Comment by sterobin** [comment]
@LightGuard , just recording here the type of ifdef and ifeval conditioning we'll need for the kogito docs source.

```
For more information about executable rule models, see
ifdef::DM,PAM[]
ifeval::["{context}" == "packaging-deploying"]
xref:executable-model-con_packaging-deploying[].
endif::[]
ifeval::["{context}" != "packaging-deploying"]
{URL_PACKAGING_DEPLOYING_PROJECT}#executable-model-con_packaging-deploying[{PACKAGING_DEPLOYING_PROJECT}].
endif::[]
endif::[]
ifdef::DROOLS,JBPM,OP[]
xref:executable-model-con_packaging-deploying[].
endif::[]
```

Meaning: If enterprise, show one thing if it's the packaging doc, or if not the packaging doc (any other doc), show the second thing. If community, just show the one thing.

Note that this relies on a :CONTEXT: variable defined in each assembly, and on anchor IDs defined for each module section, where the anchor ID must end in _{context} to be able to be reused and to point to an assembly with that module. Example anchor ID: [id='assets-executing-proc_{context}'].

This kind of thing is required in the single-sourced repo. Seems like it shouldn't be a problem if we use those anchor IDs for each section in the chapter files, and to have those anchor IDs be used in the generated module files.

**Comment by LightGuard** [comment]
@sterobin was actually look more for the bits about replaceWith

**Comment by sterobin** [comment]
@LightGuard , I pasted in the first half of my convo as well, in the same comment above. Not sure if that's what you meant, but that's all I said either way.

**Comment by LightGuard** [comment]
My move for this is to use `ifdef, `ifeval`, `xref` and `include`. Those all standard asciidoc constructs and should accomplish everything that is desired. @manaswinidas @sterobin comments?

**Comment by sterobin** [comment]
@LightGuard Yeah, I'd much prefer a standard ascii construct, specifically the `include`, which is more widely understood, and will make chap files with includes consistent with index files that already use includes for chap files overall.

**Comment by manaswinidas** [comment]
I'm okay with what @sterobin and the docs team is okay with.
