### ISSUE TITLE
Align with filenaming standards

### ISSUE THREAD

**Issue by LightGuard** [LightGuard/asciidoc-splitter#19]
There's a discussion happening at https://github.com/redhat-documentation/modular-docs/issues/111. Whatever that outcome is, we will need to align on filenames and `_{context}` (which I believe we currently are, at least wrt `_{context}`).

**Comment by manaswinidas** [comment]
@LightGuard should we close this or wait for the final conclusion of the discussion?

**Comment by LightGuard** [comment]
That could take some time :(

**Comment by LightGuard** [comment]
Pretty sure we're done with this one
