### ISSUE TITLE
Support ids that already contain `_{context}`

### ISSUE THREAD

**Issue by LightGuard** [LightGuard/asciidoc-splitter#20]
As per the sample @maxandersen added, we should support ids that already contain `_{context}` or `-{context}`.

I don't really like `-{context}` as that goes against the documentation, but... might as well support it as well.

**Comment by manaswinidas** [comment]
Solved [18eb281](https://github.com/LightGuard/asciidoc-splitter/commit/18eb2818901700ab74f53b50082d0358cf89a35c)
