### ISSUE TITLE
support image target replacement

### ISSUE THREAD

**Issue by manaswinidas** [LightGuard/asciidoc-splitter#24]
This is a use case for Kogito docs. The image paths are different for community and product versions. For the community version, all the images are in the source folder itself and for the product version, all the images are to be moved to a global _images folder and paths changed accordingly.

**Comment by LightGuard** [comment]
Gotta ask if this is something we need to do, or if this can be done easily enough with attributes. Asciidoctor has this sort of stuff already built-in if you're using attributes for the target.

**Comment by manaswinidas** [comment]
The images are mostly image blocks or inline images

**Comment by LightGuard** [comment]
That should be fine, if you do something like

    image::{images_directory}/cat.jpg[]

Then you can set {images_directory} equal to whatever is necessary based on the community, product, etc. This is really easy to do with preprocessor directives. I don't understand why this needs to be a feature the tool has to support.

Maybe Mark could chime in.

**Comment by LightGuard** [comment]
I think we're good here, yes? @manaswinidas

**Comment by manaswinidas** [comment]
yes @LightGuard
