### ISSUE TITLE
 test if utility is functionally equivalent to traditional asciidoc syntax

### ISSUE THREAD

**Issue by manaswinidas** [LightGuard/asciidoc-splitter#28]
investigate asciidoc syntax support

**Comment by LightGuard** [comment]
Thanks for the PR, good work. This will give us a good place to start for functional equivalence.

**Comment by LightGuard** [comment]
@manaswinidas I think we're good here, what do you think?

**Comment by manaswinidas** [comment]
@LightGuard yes
