### ISSUE TITLE
Don't create `_assets` folder

### ISSUE THREAD

**Issue by sterobin** [LightGuard/asciidoc-splitter#55]
### Current behavior
The splitter takes the `_images` and `_artifacts` folders and attempts to duplicate them in a new `_assets` folder, which is divided according to the folder division in `doc-content` (which only applies to the split modules anyway in the `modules` folder.

### Desired behavior
Copy over the `_images` and `_artifacts` folders exactly as they are and where they are, and don't create an `_assets` folder.

**Comment by LightGuard** [comment]
Relates to #56
