### ISSUE TITLE
Support using the splitter from repo to repo

### ISSUE THREAD

**Issue by sterobin** [LightGuard/asciidoc-splitter#59]
### Current behavior

The splitter has issues currently functioning on one git repo to another. I don't know the details, but Jason explained it had to do with discoverability of the adoc content from the root of the dir (or something). So currently can only run the splitter locally. For the splitter's purpose, running from git repo to git repo is the primary if not the sole use case for it, so working that out is will be essential.

### Desired behavior

Be able to run the spliiter successfully from a git repo source to a git repo target, whether that be any of the following variations:
* GitHub > GitLab
* GitHub > GitHub
* GitHub repo branch > same repo, diff branch
* GitLab > GitHub
* GitLab > GitLab

The last two are very unlikely, but I figure if we can just get the splitter working on whatever repo and branch, with any credentials needed, then it shouldn't matter much. This is already the target behavior today based on the splitter options available, but just not quite working yet.

**Comment by LightGuard** [comment]
I think one way to do this would be to add another option to specify where the document root is. Another option might be to include an option to specify a list of files to ignore. In this case, I think it was the "index.adoc" file. Actually, I think the ignore list is the better way to go.
