### ISSUE TITLE
Additional resources section at the bottom of chapters isn't being transferred to assemblies during the split

### ISSUE THREAD

**Issue by sterobin** [LightGuard/asciidoc-splitter#60]
Most or all chapter files in the source have the following enterprise-only section with additional resources and versioning information (for enterprise legal notice):

```
ifdef::KOGITO-ENT[]
== Additional resources
* {URL_CREATING_RUNNING}[_{CREATING_RUNNING}_]
* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
* {URL_DECISION_SERVICES}[_{DECISION_SERVICES}_]
* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]

// Versioning info
include::_artifacts/versioning-information.adoc[]
endif::[]
```

For example, see the bottom of the [configuring chapter file](https://raw.githubusercontent.com/sterobin/kie-docs/master-kogito-test-source-B/doc-content/kogito-docs/src/main/asciidoc/configuration/chap-kogito-configuring.adoc).

### Current behavior

This section of additional resources and versioning info at the bottom of the source chapter file isn't transferred to the assembly file during the split.

### Desired behavior

The section of additional resources and versioning at the bottom of the source chapter file is transferred to the assembly file during the split. All content from the entire source chapter file should be transferred exactly as is, except for module file content, which of course should be converted to includes.

**Comment by LightGuard** [comment]
Should it be added to all chapters?

**Comment by sterobin** [comment]
Well, not that it should be added. I'm saying the writer uses Additional resources whenever needed. So in this case, yes, I've added that section to all chapter files, and is often the norm, but not always. Either way, the splitter isn't adding anything, it was just not carrying that over from the source to the split version for some reason.

In sum, the splitter should copy over everything from the chap source file exactly as is to the new assembly file, _except_ the follow, which it should modify:
* Anything that starts with an anchor ID, which is a module, should be converted to includes.
* Any includes in the chap file should be converted to includes that correspond to the new split repo (i.e., modified to function given the new location and structure)

Literally everything else from the source chap file besides those two things should just be copied-pasted over to the assembly file during the split. Unless of course is :assembly: false, in which case just take only the module sections and generate the module files from them, skipping the step of doing anything for a new assembly.
