### ISSUE TITLE
Broken symlinks

### ISSUE THREAD

**Issue by handreyrc** [LightGuard/asciidoc-splitter#64]
After processing the symlinks are broken.
Notice that the symlink doc-content shall be replaced by assemblies.

*Actual:*
path /titles-enterprise/kogito-creating-running
 _artifacts -> source/kie-docs/titles-enterprise/kogito-creating-running/_artifacts
_images -> source/kie-docs/titles-enterprise/kogito-creating-running/_images
doc-content -> source/kie-docs/titles-enterprise/kogito-creating-running/doc-content

*Expected:*
path /titles-enterprise/kogito-creating-running
 _artifacts -> ../../_artifacts
_images -> ../../_images
assemblies -> ../../assemblies

In order to get it working it is also needed to update the include clause in the master.adoc.

Actual:
path /titles-enterprise/kogito-creating-running/master.adoc
// Assembly includes
include::doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc[]

Expected:
path /titles-enterprise/kogito-creating-running/master.adoc
// Assembly includes
include::assemblies/assembly-chap-kogito-creating-running.adoc[]

**Comment by LightGuard** [comment]
Please create another issue for the include fixes, trying to keep things as atomic as possible.

**Comment by handreyrc** [comment]
> Please create another issue for the include fixes, trying to keep things as atomic as possible.

Sure, I'll do it. 
Thanks
