### ISSUE TITLE
Unmatched endifs when splitting long ifdef/endif blocks

### ISSUE THREAD

**Issue by handreyrc** [LightGuard/asciidoc-splitter#66]
Splitting long blocks of ifdef/endif with the parameter “-a KOGITO-ENT=true” is resulting in unmatched endif statements preventing ccutil from building the content.

Check the source file: {source}/titles-enterprise/kogito-creating-running/doc-content/kogito-docs/src/main/asciidoc/creating-running/chap-kogito-creating-running.adoc
Go straight to the end of the file locate the endif right after the “--Additional Resources” block. The opening ifdef is located at line 1219.

Steps to reproduce:
* run the splitter
java -jar target/asciidoc-splitter-1.0-SNAPSHOT.jar -s {source} -o {output} -i index.adoc -a KOGITO-ENT=true
* go to {output}/titles-enterprise/kogito-creating-running
* run ccutil
ccutil compile --lang en-US --open
* Check ccutil output
asciidoctor: ERROR: assemblies/modules/creating-running/con-kogito-quarkus-springboot.adoc: line 14: unmatched macro: endif::[]
asciidoctor: ERROR: assemblies/assembly-kogito-creating-running.adoc: line 37: unmatched macro: endif::[]
gio: file:///home/hcunha/kie-docs/output/titles-enterprise/kogito-creating-running/build/tmp/en-US/html-single/index.html: Error when getting information for file “/home/hcunha/kie-docs/output/titles-enterprise/kogito-creating-running/build/tmp/en-US/html-single/index.html”: No such file or directory
Note: Both errors seem to have the same root cause.

Actual output:
Path: assemblies/assembly-kogito-creating-running.adoc
== Additional resources
\* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
\* {URL_DECISION_SERVICES}[_{DECISION_SERVICES}_]
\* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
\* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]
**endif::[]**

Expected output:
Following the Target reference
Path: assemblies/assembly-kogito-creating-running.adoc
**ifdef::KOGITO-ENT[]**
== Additional resources
\* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
\* {URL_DECISION_SERVICES}[_{DECISION_SERVICES}_]
\* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
\* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]
**endif::[]**

**Comment by LightGuard** [comment]
Yep, I know about this one. I don’t have a solution just yet.
