### ISSUE TITLE
Files generated with prefix “unknown-”

### ISSUE THREAD

**Issue by handreyrc** [LightGuard/asciidoc-splitter#67]
The following files are being generated with the prefix “unknown-”:
./modules/creating-running/unknown-chap-kogito-creating-running.adoc
./modules/configuration/unknown-chap-kogito-configuring.adoc

Following the Target reference, these files shouldn’t exist and its content should be compiled on top of the following files respectively:
./assemblies/assembly-kogito-creating-running.adoc
./assemblies/assembly-kogito-configuring.adoc

**Comment by LightGuard** [comment]
Yeah, it’s the preamble section. Haven’t looked into why this is happening yet.
