### ISSUE TITLE
xrefs: Included direcly causing ccutil compiling errors

### ISSUE THREAD

**Issue by handreyrc** [LightGuard/asciidoc-splitter#68]
Splitter is including xrefs not protected by makros breaking the ccutil compilation.
**Splitter parameters:**
java -jar target/asciidoc-splitter-1.0-SNAPSHOT.jar -s {source} -o {output} -i index.adoc -a KOGITO-ENT=true

**ccutil output:**
path:output/titles-enterprise/kogito-creating-running
Unknown ID or title "con-kogito-runtime-events_kogito-configuring", used as an internal cross reference

Actual:
path: output/modules/creating-running/ref-kogito-glossary.adoc
\.Additional resources
\* {URL_CONFIGURING_KOGITO}#con-kogito-runtime-events_kogito-configuring[_{PRODUCT} runtime events_]
\* {URL_CONFIGURING_KOGITO}#con-data-index-service_kogito-configuring[_{PRODUCT} Data Index Service_]
\* xref:con-kogito-runtime-events_kogito-configuring[]
\* xref:con-data-index-service_kogito-configuring[]

Expected: 
path: target/modules/creating-running/ref-kogito-glossary.adoc
\.Additional resources
\\ifdef::KOGITO-ENT[]
\* {URL_CONFIGURING_KOGITO}#con-kogito-runtime-events_kogito-configuring[_{PRODUCT} runtime events_]
\* {URL_CONFIGURING_KOGITO}#con-data-index-service_kogito-configuring[_{PRODUCT} Data Index Service_]
\endif::[]
**ifdef::KOGITO-COMM[]**
\* xref:con-kogito-runtime-events_kogito-configuring[]
\* xref:con-data-index-service_kogito-configuring[]
**endif::**

**Comment by LightGuard** [comment]
I think I solved this with the previous commit. Please update/close as needed.

**Comment by handreyrc** [comment]
Yes, it is covered by the last commit.
Great job by the way!
