### ISSUE TITLE
include files do not exist

### ISSUE THREAD

**Issue by handreyrc** [LightGuard/asciidoc-splitter#69]
After running the splitter some include references are broken preventing the ccutil to generate the content.
It is happening because the include files are not being created in /assemblies/modules/{dir}.

ccutil output:
path: titles-enterprise/kogito-developing-decision-services
asciidoctor: ERROR: assemblies/modules/decision-services/con-drl-rules-actions.adoc: line 23: include file not found: /docs/kie-docs/output/titles-enterprise/kogito-developing-decision-services/assemblies/modules/decision-services/modules/decision-engine/con-property-change-listeners.adoc
asciidoctor: ERROR: assemblies/modules/decision-services/proc-drl-rules-central-create.adoc: line 201: include file not found: /docs/kie-docs/output/titles-enterprise/kogito-developing-decision-services/assemblies/modules/decision-services/chap-kogito-using-dmn-models.adoc
asciidoctor: ERROR: assemblies/modules/decision-services/ref-decision-tables-attributes.adoc: line 79: include file not found: /docs/kie-docs/output/titles-enterprise/kogito-developing-decision-services/assemblies/modules/decision-services/chap-kogito-using-dmn-models.adoc

Picking the first error, it comes from the source file:
/doc-content/kogito-docs/src/main/asciidoc/decision-services/chap-kogito-using-drl-rules.adoc
It references other chap-file and also passes a "Tag" for locating the content:
882: include::{asciidoc-dir}/decision-engine/chap-kogito-decision-engine.adoc[tags=con-property-change-listeners]
path: /doc-content/kogito-docs/src/main/asciidoc/decision-engine/chap-kogito-decision-engine.adoc

After processing 
Actual:
path: output/assemblies/modules/decision-services/con-drl-rules-actions.adoc
23: include::modules/decision-engine/con-property-change-listeners.adoc[leveloffset=+1]
*The include is correct. However, the file does not exist.*

Expected:
The include files should be generated.

**Comment by LightGuard** [comment]
So the one that looks like `include::chap-kogito-using-dmn-models.adoc[tags=con-kogito-service-execution]` There's actually no path there. That chap file doesn't exist, however, `decision-services/chap-kogito-using-dmn-models.adoc` does, but the splitter doesn't really have a good way of knowing that from any other directory with the same file name (which, yes should not happen) but this one I'm going to punt back and say the source needs to be fixed so it correctly references the file location.

**Comment by handreyrc** [comment]
This issue was solved by with the last commit and the patch.
Thanks!
