### ISSUE TITLE
replace-with: ccutil compiles but the content is not being included

### ISSUE THREAD

**Issue by handreyrc** [LightGuard/asciidoc-splitter#71]
The replace-with is working and generating the includes. However, after running ccutil the content is not being included in the html.

e.g.
[replace-with="../creating-running/ref-kogito-app-examples.adoc" replace-with-id="ref-kogito-app-examples"]
link:{asciidoc-dir}/creating-running/chap-kogito-creating-running.adoc[My Test].

Actual output:
include::../creating-running/ref-kogito-app-examples.adoc[tags=ref-kogito-app-examples]

Expected output:
include::../creating-running/ref-kogito-app-examples.adoc[leveloffset=+1]

**Comment by LightGuard** [comment]
Does it make sense to have a replace-with-id ? Should it simply be replace-with?

**Comment by handreyrc** [comment]
I think it is better to keep as flexible as possible.
Maybe we could fix it this way:
[replace-with="../creating-running/ref-kogito-app-examples.adoc" replace-with-param="tag=ref-kogito-app-examples"]
output -> include::../creating-running/ref-kogito-app-examples.adoc[tags=ref-kogito-app-examples]

[replace-with="../creating-running/ref-kogito-app-examples.adoc" replace-with-param="leveloffset=+1"]
output-> include::../creating-running/ref-kogito-app-examples.adoc[leveloffset=+1]
