### ISSUE TITLE
Conditions and meta tags not retained properly for "= Additional resources" in each split assembly

### ISSUE THREAD

**Issue by sterobin** [LightGuard/asciidoc-splitter#81]
### Current behavior

This is most likely related to #80 , but at the end of each chapter file in the source repo there is an "= Additional resources" section that's conditioned for enterprise only and that contains a `[role="_additional-resources"]` tag, as follows:

```
ifdef::KOGITO-ENT[]
[role="_additional-resources"]
== Additional resources
* {URL_CREATING_RUNNING}[_{CREATING_RUNNING}_]
* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]
endif::[]
```

The expectation again with these conditions is that they will be retained exactly as is in the conversion, so that that the bottom of the new assembly you'll see the above same conditioned section. And the expectation is that any tags like that will be retained too.

Instead, today the start ifdef is removed and the endif is left in place, which breaks the build for every assembly. Also, for some reason the `[role="_additional-resources"]` tag, which is required for Pantheon 2, is getting removed.

This is how the above looks after the split:

```
== Additional resources

* {URL_CREATING_RUNNING}[_{CREATING_RUNNING}_]
* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]
endif::[]
```

Example source chap file with the correct conditions: https://raw.githubusercontent.com/kiegroup/kie-docs/master-kogito/doc-content/kogito-docs/src/main/asciidoc/dmn/chap-kogito-using-dmn-models.adoc

Example converted assembly with the start ifdef and   removed: https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/kie-docs-translator/-/blob/master-kogito/assemblies/assembly-kogito-using-dmn-models.adoc

### Target behavior

Retain conditions and tags during the split, without manipulation or removal. The following section, for example, would be transferred identically from the chapter to assembly after the split:

```
ifdef::KOGITO-ENT[]
[role="_additional-resources"]
== Additional resources
* {URL_CREATING_RUNNING}[_{CREATING_RUNNING}_]
* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]
endif::[]
```

### Resources

- Source repo and branch used: https://github.com/kiegroup/kie-docs/tree/master-kogito
- Target repo and branch used: https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/kie-docs-translator/-/tree/master-kogito/
- Splitter command used:
```
target/asciidoc-splitter-1.0-SNAPSHOT-bin/bin/asciidoc-splitter.sh -sr git@github.com:kiegroup/kie-docs.git -sb master-kogito -or git@gitlab.cee.redhat.com:red-hat-jboss-bxms-documentation/kie-docs-translator.git -ob master-kogito -i index.adoc
```

**Comment by LightGuard** [comment]
"Retain conditions and tags during the split, without manipulation or removal." That cannot be done.

I'll see if I can tweak it some more. Please provide a test case.

**Comment by sterobin** [comment]
@LightGuard "Please provide a test case." Don't know what you mean, I've given all the details above.

**Comment by sterobin** [comment]
As discussed in chat, you should have all the info and links that you need above to create a branch or download the zip for a test case.
