### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by bhardesty** [LightGuard/asciidoc-splitter#83]
I tried installing asciidoc-splitter, but the build fails each time with the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project asciidoc-splitter: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by LightGuard** [comment]
Thanks, I'll take a look.

**Comment by LightGuard** [comment]
Which version of maven are you using and what is the command you're executing?

**Comment by LightGuard** [comment]
I just ran the following:
```
./mvnw clean install
```
From the project directory and everything went through just fine.

**Comment by bhardesty** [comment]
Thanks - I just updated maven and asciidoc-splitter builds fine now. Sorry for the false alarm; I didn't even think about the fact that my maven install was (very) out of date.
