### ISSUE TITLE
Splitter fails without at least 2 line breaks before the first module section in an assembly

### ISSUE THREAD

**Issue by sterobin** [LightGuard/asciidoc-splitter#89]
@LightGuard I had a docs PR wherein the splitter was failing for strange reasons pointing to the first module in the assembly. I tested locally by strategically commenting in and out various parts of the chapter and running the splitter locally, and discovered that only by adding this additional line break shown here https://github.com/redhat-developer/app-services-guides/pull/144/files#diff-658974d4b95a96305473a76ce955d1e9398650c2d487014a9d0746c00dd964dcR48  that the splitter then ran successfully. It's an added line break between the single intro paragraph to the chapter and the first module of the chapter. This hasn't ever come up before because all other chapters in our repo coincidentally have at least two intro paragraphs or chapter-level prereqs or some sort of content that naturally adds more than one line break before the first module. So this is the first time we have a single intro paragraph and then the first module that follows, which apparently causes an issue unless more content is added.

Any thoughts? Thanks so much.

@pmuir Just FYI ^^

**Comment by LightGuard** [comment]
No idea, honestly. I could spend time, but if you have a solution, it may not be worth it to find the actual issue.
