### ISSUE TITLE
non-adoc includes files are not moved/swizzled

### ISSUE THREAD

**Issue by maxandersen** [LightGuard/asciidoc-splitter#9]
see:
https://github.com/infinispan/infinispan/blob/master/documentation/src/main/asciidoc/topics/query.adoc

vs

https://github.com/maxandersen/infinispan/blob/asciidocsplitterexample/documentation/src/main/splitterresult/query.adoc

notice how things like `link:config_examples/indexing_async.xml[]` are not resolvable.

probably a few ways we can handle this by either copying things in relative to the adoc or otherwise have a default include path if such thing exists in asciidoctor or we have to "swizzle" these relative paths to work.

i reckon image and other kind of external referencing with relative paths would need similar treatment.

**Comment by LightGuard** [comment]
Yeah...

Relative things are going to be a bit of a pain depending on where they live.

**Comment by maxandersen** [comment]
if we copy them all relatively everything should be fine actually should it not ?

**Comment by LightGuard** [comment]
Where do you copy, into the modules directory, the root directory, or rewrite them to be some resources directory?

If something is referenced relative to a resources directory then that adoc source is placed into the modules directory, that link is now void. I think rewriting includes like that and place all that stuff into a resources directory may be the best option.

**Comment by LightGuard** [comment]
My thoughts:
Additional assets can go into an "assets" directory that would live at the same level as the "assemblies" and "modules" directory. We'll need to rewrite the references to them, and this is where things will get a little tricky.

**Comment by LightGuard** [comment]
Fixed in 32fae4b
