### ISSUE TITLE
Verify that the splitter converts either `chap-` or `assembly-` prefix in anchor ID to `assembly-`

### ISSUE THREAD

**Issue by sterobin** [LightGuard/asciidoc-splitter#95]
@LightGuard I know for certain that today the splitter converts `chap-` to `assembly-` in anchor IDs, by design. Can we make sure that if someone just chooses to use the `assembly-` prefix upstream as well, that the splitter can just ignore it? Or convert it to the same value downstream? Basically, we need to be sure that people can use either of those prefixes upstream and have it turn out as `assembly-` downtream. We can't impose the strict requirement that prefixes _must_ be `chap-`, only that prefixes _can_ be `chap-`. Thus both should be supported.

**Comment by LightGuard** [comment]
Okay, well, what are your expected outcomes?

**Comment by sterobin** [comment]
Thank you @LightGuard !
